In [1]:
my_list = [1,2,3]

In [26]:
import numpy as np

In [5]:
#casting the list as numpy array

arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [10]:
#2-D array or matrix

my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
mat_arr = np.array(my_mat) #casting list of lists aas 2-d array

In [9]:
mat_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
#Generating arrays
new_arr = np.arange(0,10)

In [14]:
new_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr2 = np.arange(0,101,2) #even numbers
arr2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [17]:
arr3 = np.arange(1,100,2) #odd numbers
arr3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [18]:
#Generating an array of zeroes
np.zeros(5)  #1-d array of zeroes

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((3,5)) #2-d array of zeroes by passing a tuple stating number of rows and number of columns


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
#generating array of ones


np.ones(4) #1-d array of ones

array([1., 1., 1., 1.])

In [22]:
np.ones((6,2)) #2-d array of ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
#LinSpace --> returns evenly spaced numbers in a specific interval

np.linspace(0,5,100) #100 --> number of numbers needed between 0 and 5

#it is a 1-d array

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [25]:
#creating an identity matrix --> 2-d square matrix having only the diagonals elements as 1 and rest as 0

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#generating random numbers
np.random.rand(5) #1-d array of random numbers

array([0.26895356, 0.32064446, 0.172101  , 0.10662027, 0.77876823])

In [30]:
np.random.rand(4,4) #2-d array of random numbers

array([[0.50824587, 0.66530318, 0.16621951, 0.07624362],
       [0.64934501, 0.78996481, 0.42229918, 0.10692859],
       [0.57754265, 0.5131306 , 0.40610649, 0.24290132],
       [0.73509855, 0.31232636, 0.11382494, 0.30497852]])

In [32]:
#generating sample from a standard gaussian distribution centered around 0
np.random.randn(5)

array([-0.90468884, -1.23953915,  0.17510635,  1.07092096, -1.17551489])

In [34]:
#generating random integers 
np.random.randint(1,100,10) #generating 10 random integers between 1 and 100

array([86, 37, 66, 74, 41, 14, 75, 93, 80, 17])

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
rand_arr = np.random.randint(0,50,10)

In [38]:
rand_arr

array([37, 31, 24, 49, 21,  2, 26, 46, 39,  1])

In [39]:
#reshaping the array
arr.reshape(4,4)

#total elements in the orginal array must match the size of matrix it is being reshaped in

ValueError: cannot reshape array of size 25 into shape (4,4)

In [40]:
arr.reshape(3,8)

ValueError: cannot reshape array of size 25 into shape (3,8)

In [41]:
arr.reshape(5,5) # 5*5 = 25 => number of elements in the arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
rand_arr.max() #maximum values of the array

49

In [43]:
rand_arr.min() #minimum value in the array

1

In [44]:
rand_arr

array([37, 31, 24, 49, 21,  2, 26, 46, 39,  1])

In [45]:
rand_arr.argmax() #returns the index location of the max value in the array

3

In [47]:
rand_arr.argmin() #returns the index location of the min value in the array

9

In [49]:
#to get the shape of the array
arr.shape

(25,)

In [50]:
arr = arr.reshape(5,5)

In [51]:
arr.shape

(5, 5)

In [52]:
# to know the data type of array
arr.dtype

dtype('int32')

In [56]:
#importing only the specific method from the module
from numpy.random import randint
randint(1,50,5)

array([27, 34, 34, 37, 41])

### Indexing and Selection

In [57]:
import numpy as np

In [58]:
arr = np.arange(0,11)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr[8] #passing the index to get the element

8

In [61]:
arr[:5] #to get the elements starting from beginning till the index 5(excluding)

array([0, 1, 2, 3, 4])

In [62]:
arr[1:4]

array([1, 2, 3])

In [63]:
arr[5:] #from a certain element at index 5 till the end

array([ 5,  6,  7,  8,  9, 10])

In [64]:
#Broadcasting the value
arr[:5] = 100

In [65]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [66]:
arr = np.arange(0,11)

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
slice_of_arr = arr[:4]

In [69]:
slice_of_arr

array([0, 1, 2, 3])

In [70]:
slice_of_arr[:] = 88 #broadcasting
slice_of_arr

array([88, 88, 88, 88])

In [71]:
arr #broadcasting the value in the slice has made the changes in the original array

#hence the data is not copied in the slice, it is just a reference to the original array

array([88, 88, 88, 88,  4,  5,  6,  7,  8,  9, 10])

In [72]:
#Copying the array explicitly
arr_copy = arr.copy()

In [73]:
arr_copy

array([88, 88, 88, 88,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr_copy[0:3] = 77

In [75]:

arr_copy

array([77, 77, 77, 88,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr #original array is still intact even after the broadcasting

array([88, 88, 88, 88,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr_2d = [[3,6,9],[2,12,72],[5,15,35]]

In [81]:
arr_2d = np.array(arr_2d)
arr_2d

array([[ 3,  6,  9],
       [ 2, 12, 72],
       [ 5, 15, 35]])

In [82]:
#Indexing and slicing in the matrix
arr_2d[0][0] #getting the element at 0th row and 0th column

3

In [83]:
arr_2d[1][0]

2

In [84]:
arr_2d[0] #0th row

array([3, 6, 9])

In [87]:
arr_2d[1][2] #double bracket notation

72

In [88]:
#single bracket comma notation
arr_2d[1,2]

72

In [89]:
arr_2d[2,1]

15

In [90]:
# slicing the sub-matrix
arr_2d


array([[ 3,  6,  9],
       [ 2, 12, 72],
       [ 5, 15, 35]])

In [91]:
arr_2d[:2,1:] #rows 0 and 1 will be included (2 not included) and columns from 1 to end

array([[ 6,  9],
       [12, 72]])

In [92]:
arr_2d[1:,1:]

array([[12, 72],
       [15, 35]])

In [93]:
arr_2d[1:,:2]

array([[ 2, 12],
       [ 5, 15]])

In [94]:
#Conditional Slicing

arr2d = np.arange(0,11)

In [95]:
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr2d > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [100]:
arr_2d

array([[ 3,  6,  9],
       [ 2, 12, 72],
       [ 5, 15, 35]])

In [102]:
#Conditional slicing for divisible by 3
bool_arr = arr_2d % 3 == 0

In [103]:
bool_arr

array([[ True,  True,  True],
       [False,  True,  True],
       [False,  True, False]])

In [105]:
#conditionally selecting the elements for which the condition of divisibility by 3 holds true
arr_2d[bool_arr]

array([ 3,  6,  9, 12, 72, 15])

### Numpy Operations

In [106]:
import numpy as np

In [107]:
#Array with Array operations

#Element wise operations
arr = np.arange(0,11)

In [108]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr_add = arr + arr

In [110]:
arr_add

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [111]:
arr_sub = arr - arr

In [112]:
arr_sub

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [113]:
arr_mul = arr*arr

In [114]:
arr_mul 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [117]:
#Array with scalar operations
arr_add100 = arr + 100
arr_add100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [118]:
1/0

ZeroDivisionError: division by zero

In [120]:
arr_div = arr/arr
arr_div  #0/0 is given as NAN --> It doesn't give the error

C:\Users\coolt\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [121]:
arr_x = 1/arr
arr_x

C:\Users\coolt\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [122]:

arr_pow3 = arr ** 3 #Cube
arr_pow3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [123]:
#Universal Array Operations (ufunc)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [124]:
arr_sqrt = np.sqrt(arr) #square root
arr_sqrt

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [125]:
#exponential
arr_exp = np.exp(arr)
arr_exp

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [126]:
np.max(arr)

10

In [127]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [128]:
np.log(arr)

C:\Users\coolt\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])